### ISSUE TITLE
The program is still there, but I can't control it.

### ISSUE THREAD

**Issue by badboycxcc** [Enelg52/KittyStager#13]
<img width="988" alt="截屏2023-03-17 下午10 24 21" src="https://user-images.githubusercontent.com/72059221/225932558-20051b15-f2bc-4c7c-b54c-9bb645fadcec.png">

<img width="666" alt="截屏2023-03-17 下午10 24 49" src="https://user-images.githubusercontent.com/72059221/225932527-b207eb5a-dcb6-480d-8e76-71142805d5a7.png">

<img width="725" alt="截屏2023-03-17 下午10 24 37" src="https://user-images.githubusercontent.com/72059221/225932546-7ad36ff8-85dc-48b6-a3c3-3f6e6c906f65.png">

**Comment by Enelg52** [comment]
Hello there ! It should be fixed. If not, feel free to reach me on discord Enelg#9993

**Comment by badboycxcc** [comment]
The problem still exists, and a friend request has been sent.
